[package]
name = "rust_audio_player"
version = "0.1.0"
edition = "2024"

[dependencies]
rodio = "0.21"
walkdir = "2.5"
eframe = "0.32"
egui = "0.32"
catppuccin-egui = { version = "5.6.0", default-features = false, features = ["egui32"] }
symphonia = { version = "0.5", features = ["mp3", "wav"] }